spec:
  name: zkt-fel
  services:
    - name: web
      http_port: 8080
      instance_size_slug: basic-xxs
      dockerfile_path: ./Dockerfile
      envs:
        - key: FEL_G4S_SOAP_URL
          value: https://fel.g4sdocumenta.com/webservicefront/factwsfront.asmx
        - key: FEL_G4S_SOAP_ACTION
          value: http://www.fact.com.mx/schema/ws/RequestTransaction
        - key: FEL_G4S_SOAP_VERSION
          value: "1.1"
        - key: FEL_G4S_REQUESTOR
          value: 425C5714-AA9E-4212-B4AA-75BD70328030
        - key: FEL_G4S_COUNTRY
          value: GT
        - key: FEL_G4S_ENTITY
          value: "81491514"
        - key: FEL_G4S_USER
          value: 425C5714-AA9E-4212-B4AA-75BD70328030
        - key: FEL_G4S_USERNAME
          value: ADMINISTRADOR
        - key: FEL_G4S_PASS
          value: TVAmE7Wk
          scope: RUN_TIME
          type: SECRET
        - key: FEL_G4S_LIST_TX
          value: LOOKUP_GUATEMALIAN_ISSUED
        - key: FEL_G4S_DATAX_ENCODE
          value: base64
        - key: FEL_G4S_ESTABLECIMIENTO
          value: "4"

        - key: DB_CONNECTION
          value: mysql
        - key: DB_HOST
          value: your-mysql-host
        - key: DB_PORT
          value: "3306"
        - key: DB_DATABASE
          value: zkt
        - key: DB_USERNAME
          value: root
        - key: DB_PASSWORD
          value: ""
          scope: RUN_TIME
          type: SECRET
